# Generated by Django 5.0.6 on 2024-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='color',
            field=models.CharField(default='light', max_length=5),
        ),
    ]
