# Generated by Django 5.0.6 on 2025-01-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
