# Generated by Django 5.0.6 on 2024-12-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='chat',
            name='name2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
