# Generated by Django 5.0.6 on 2024-12-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chat_name1_remove_chat_name2_chatname'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='static/messages_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_to_message', to='chats.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
