# Generated by Django 5.0.6 on 2024-12-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_message_file_content_message_replied_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chats.message'),
        ),
    ]
