# Generated by Django 5.0.6 on 2024-12-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_message_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
