# Generated by Django 5.0.6 on 2024-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_message_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='media/messages_files/'),
        ),
    ]
