# Generated by Django 5.0.6 on 2024-12-27 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0011_remove_message_liked_message_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
