# Generated by Django 5.0.6 on 2025-01-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_alter_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
