# Generated by Django 5.0.6 on 2024-11-16 10:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(blank=True, related_name='receivers_of_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SystemOfNotifications',
        ),
    ]
