# Generated by Django 5.0.6 on 2024-12-11 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_created_at_notification_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='who_sent',
            field=models.ManyToManyField(related_name='who_sent_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ManyToManyField(related_name='receivers_of_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
